### ISSUE TITLE
Depend on parking_lot 0.12

### ISSUE THREAD

**Issue by dvtomas** [palfrey/serial_test#57] opened 2022-05-27 09:54 UTC
New version of parking_lot has been released, it would reduce my dependencies if serial_test depends on it

**Comment by palfrey** [comment] 2022-05-27 10:50
Duplicate of #52. See https://github.com/palfrey/serial_test/issues/52#issuecomment-1079966675

**Closed by palfrey** 2022-05-27 10:50 UTC
