### ISSUE TITLE
Test blocking

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [palfrey/serial_test#60] opened 2022-06-08 17:11 UTC
In writing a test project, the library seems to often block.

My tests:
```rust
#[cfg(test)]
mod tests {
    use std::{thread,time::Duration};
    use rand::{thread_rng,Rng};
    use serial_test::{serial,parallel};
    const MAX_DURATION: Duration = Duration::from_secs(1);
    const FAILURE_RATE: u8 = 10;
    // Every test sleep for 0..MAX_DURATION then has a FAILURE_RATE % change to fail.
    fn test() {
        let mut rng = thread_rng();
        let duration = rng.gen_range(Duration::ZERO..MAX_DURATION);
        println!("{:.2?}",duration);
        thread::sleep(duration);
        assert!(rng.gen_range(0..100) > FAILURE_RATE);
    }
    #[test]
    #[serial]
    fn test1s() {
        test();
    }
    #[test]
    #[serial]
    fn test2s() {
        test();
    }
    #[test]
    #[serial]
    fn test3s() {
        test();
    }
    #[test]
    #[serial]
    fn test4s() {
        test();
    }
    #[test]
    #[parallel]
    fn test1p() {
        test();
    }
    #[test]
    #[parallel]
    fn test2p() {
        test();
    }
    #[test]
    #[parallel]
    fn test3p() {
        test();
    }
    #[test]
    #[parallel]
    fn test4p() {
        test();
    }
    #[test]
    #[parallel]
    fn test5p() {
        test();
    }
    #[test]
    #[parallel]
    fn test6p() {
        test();
    }
    #[test]
    #[parallel]
    fn test7p() {
        test();
    }
    #[test]
    #[parallel]
    fn test8p() {
        test();
    }
    #[test]
    #[parallel]
    fn test9p() {
        test();
    }
}
```
The result:
```
PS C:\Users\jcawl\Projects\ci-testing> cargo test -- --nocapture
   Compiling ci-testing v0.1.0 (C:\Users\jcawl\Projects\ci-testing)
    Finished test [unoptimized + debuginfo] target(s) in 0.67s
     Running unittests src\lib.rs (target\debug\deps\ci_testing-0e10227a2bfd9068.exe)

running 13 tests
356.03ms
832.31ms
181.79ms
727.84ms
984.31ms
test tests::test6p ... ok
699.36ms
test tests::test8p ... ok
test tests::test3p ... ok
thread 'tests::test7p' panicked at 'assertion failed: rng.gen_range(0..100) > FAILURE_RATE', src\lib.rs:14:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::test7p ... FAILED
489.77ms
test tests::test5p ... 315.09ms
528.62ms
ok
test tests::test4p ... ok
test tests::test1p ... ok
thread 'tests::test2p' panicked at 'assertion failed: rng.gen_range(0..100) > FAILURE_RATE', src\lib.rs:14:9
test tests::test2p ... FAILED
test tests::test1s has been running for over 60 seconds
test tests::test2s has been running for over 60 seconds
test tests::test3s has been running for over 60 seconds
test tests::test4s has been running for over 60 seconds
```

**Comment by LovecraftianHorror** [comment] 2022-06-08 23:17
Still reproduces on `70dd0a89a5c337cf07d4286474f5bb44a199d8f4` and minimized

```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
serial_test = { git = "https://github.com/palfrey/serial_test" }
```

```rust
use serial_test::{parallel, serial};

#[test]
#[serial]
fn serial_test() {}

#[test]
#[parallel]
fn parallel_test() {
    panic!();
}
```

```text
running 2 tests
test parallel_test ... FAILED
test serial_test has been running for over 60 seconds
```

---

The serial test blocks forever if it runs after the parallel test. Things run fine if the serial test runs first though

**Comment by palfrey** [comment] 2022-06-09 06:34
I'm pretty sure that's what's happening is that the unlock that normally happens at the end of a test is failing to occur because of the panic. There's a test with `should_panic` but I'm guessing that wraps things such that it doesn't trip this. I've got a few thoughts on how to fix this, but it'll probably be the weekend before I might have time to look at this.

**Comment by JonathanWoollett-Light** [comment] 2022-06-09 08:50
In [sequential-test](https://github.com/JonathanWoollett-Light/sequential-test) I handle this with:
```rust
// Lock
let res = std::panic::catch_unwind(|| { /* test code */} );
// Unlock
if let Err(err) = res {
    std::panic::resume_unwind(err);
}
```

**Comment by palfrey** [comment] 2022-06-09 09:12
> This does add the overhead where serial tests are not truly serial

Given the end-users test code will still run in serial, I'm happy with that behaviour :) That's basically how I was going to solve things, so glad to see someone else coming to the same conclusion.

**Comment by LovecraftianHorror** [comment] 2022-06-22 03:03
It seemed to work perfectly in all the examples I had to throw at it :+1:

**Comment by palfrey** [comment] 2022-06-22 17:29
> It seemed to work perfectly in all the examples I had to throw at it 👍

Awesome. I've merged #61, and will see if I've got time to look at https://github.com/palfrey/serial_test/issues/58 over about the next week. If not, I'll release a 0.7.1 fixing this, otherwise I'll do #58 and do 0.8.0 with both fixes.

**Closed** 2022-06-22 17:28 UTC

**Comment by palfrey** [comment] 2022-06-25 22:02
FYI, 0.8.0 just got released with this and `file_parallel` support

**Comment by kevin-june** [comment] 2022-10-12 18:47
I am encountering this issue when using version 0.9.0. I'm still working on reproducing the bug with an example that doesn't use proprietary code. If I can, I'll be sure to post an example in a new issue.
